### ISSUE TITLE
Trying to train using AWS

### ISSUE THREAD

**Issue by shadaron** [dribnet/perceptionengines#2]
Trying to train/plan images with the Amazon Rekognition instead of the keras imagenet models.
Scoring already works great. I've tried many things like adding the aws to the model_groups in utils.py  but with no luck. Currently I get the error:

Traceback (most recent call last):
  File "plan_image.py", line 587, in <module>
    main()
  File "plan_image.py", line 578, in main
    optimize(outdir, array_to_image, objective_fn, iterations=args.max_iterations, numpop=args.num_pop, preview_size=render_size, num_lines=args.num_lines, initial_array=initial_array, init_step=args.init_step, rand_head=args.random_head, head_length=args.header_length)
  File "plan_image.py", line 278, in optimize
    rewards, _ = f(w_try)
  File "plan_image.py", line 157, in f_optimize
    full_predictions = np.array(full_predictions)
ValueError: could not broadcast input array from shape (100,1) into shape (100)

I'm a beginner so I'm a bit lost. Hope you can help me out!

**Comment by dribnet** [comment]
This should work out of the box on the current version after updating the `--networks` option - but with lots of caveats. I tested this by having the planning system create an image that AWS would think is a "hand":

```bash
python plan_image.py \
  --outdir outputs/aws_hand \
  --networks aws:+hand \
  --target-class 1 \
  --random-seed 1060 \
  --num-lines 16 \
  --num-pop 24 \
  --max-attempts 5 \
  --max-iterations 50
```

The result was this image:
![best](https://user-images.githubusercontent.com/945979/71820515-2b9bb680-30f4-11ea-83ac-4b31473d5edc.png)

Which scored fairly well on AWS object detection for hand:

<img width="1014" alt="Screen Shot 2020-01-07 at 2 21 40 AM" src="https://user-images.githubusercontent.com/945979/71820809-330f8f80-30f5-11ea-9cab-0fd0aca99833.png">

Running it a few times I was even able to get a similar shape that had a top-1 prediction label of "hand" on AWS:

<img width="990" alt="Screen Shot 2020-01-07 at 2 21 09 AM" src="https://user-images.githubusercontent.com/945979/71820811-3571e980-30f5-11ea-8f4f-32eb8a898694.png">

Now let's get to the caveats before explaining the arguments in more detail:

 * The result (IMHO) is not as conceptually interesting because you've likely overfit and so this image probably doesn't generalize to other trained networks.

 * This is slow and potentially expensive. Each iteration makes a population of candidates and tests them all. by default a population is 100, so if this runs 100 iterations then you've made 10,000 API calls.

 * This won't work for arbitrary labels (for example "skunk" or "library") because APIs often don't return confidence scores for low scoring labels - so the entire population will effectively score a zero and you're stuck.

So some strategies for getting this to work which explains some of those arguments above:

  * decreasing the population size with `num-pop` option (runs faster and costs less)

  * give up sooner by reducing `max-attempts` and `max-iterations` so we don't spend too many API calls on any one run

  * unfortunately, the `target-class` argument still has to be provided even though this is effectively ignored in this case so it can be anything

  * since the population is smaller, it can help to use lower values for `num-lines` - this effectively shrinks the search space by drawing fewer primitives

  * if you are having trouble finding a label that works, you can instead draw several random shapes, submit that to the API to see all possible labels, and then optimize on your most promising result

Hope that's helpful. Good luck and would be interested in seeing what you come up with.

**Comment by shadaron** [comment]
It's awesome. Sadly I can't get the label 'person' or 'woman, 'man', 'human' ect to work. You mention in your last point that I could try drawing several random shapes and optimize it from there. Do you mean just to pick the most promising label to train something? or do you mean that I could draw a human like figure, see if it works on API, and use that drawing as a start to optimize it from there?

Anyways 'face' works which is a good alternative. I'll try some other things as well.
Thanks again!

**Comment by dribnet** [comment]
Great. Yes, I meant just picking the most promising label and then optimising for that one.

**Comment by shadaron** [comment]
allright! Btw, would this method also work for Google's API? I might try that as well when I receive my credit card this week (which is needed for google's API).

**Comment by dribnet** [comment]
yes, technique is the same for google's api and same caveats apply.

**Comment by shadaron** [comment]
Can I ask you one more question? I'm trying to curve the lines so I can trigger some labels quicker. But I'm struggling for hours now without result. Could you tell me how you did that? If you want to keep things secret I'll understand!

**Comment by dribnet** [comment]
Unfortunately you're kind of on your own there as there are million different ways to draw images with Python, none are that great, and mine are specialised routines that capture my own preferred drawing style. But there's definitely no reason to be limited to the lines and circles in my example code - you should in principle be able to use other drawing APIs such as python-cairo or other drawing packages ( eg: @inconvergent uses this here: https://github.com/inconvergent/fracture )

**Comment by shadaron** [comment]
Thanks! I've tried a few different things. I ended up liking the rectangles the most! Like this koala: https://i.imgur.com/5dZ6jXC.png and the sea_shore: https://i.imgur.com/OKnONjh.png 
It doesn't work with all scoring models but I think it's cool! Am I allowed to use this for a school project? I'll of course credit you for the code. I had a presentation recently about the perception engines, so most people in my class already know about you. Thanks again for all the help!

**Comment by dribnet** [comment]
of course - glad this worked out for you and thanks for sharing those results.

**Comment by dribnet** [comment]
Hi @shadaron - let me know if you might be interested in posting your square drawing code as a merge request to the project as I sometimes get others asking about drawing routines and I think it would make an interesting example.

**Comment by dribnet** [comment]
Hi again @shadaron - I really liked the pixelated style you came up with and thought it was really striking with the koala. I hope you don't mind that I [posted your koala example](https://twitter.com/dribnet/status/1388831574989357061) on Twitter as an example of how this codebase could be used with a custom renderer and would be happy to credit/tag you as well, etc. if you'd like.

**Comment by shadaron** [comment]
Hi @dribnet Tom! I'm glad to hear you like it! Of course you can post it. I only altered a very tiny bit of your code after all. I had made a video showing the progress of your code. I dug it up and just uploaded it here: https://www.youtube.com/watch?v=2jaGAYV9Wds (the scores aren't precisely accurate)
